name: "checkpoints/scannet/online_distill_all_sample_loc/distill.withcolor.global_ray_dir.ray_valid.knn.self_attention1.woinitpcd.knn8.gap0.4.create2.relative_thresh.all_sample_loc.teacher24.studenall.radius1"

data_root: "/mnt/cache/caiyingjie/data/scannet/scans/"
pre_d_est: "../checkpoints/MVSNet/model_000014.ckpt"
checkpoints_dir: "../checkpoints/scannet/"
resume_dir: "../checkpoints/init/dtu_dgt_d012_img0123_conf_agg2_32_dirclr20"

plr: 0.02
lr: 0.0005

embed_init_type: 'model'
progressive_distill: 1

# ddp init type
ddp_init_type: 'new'

agg_type: 'attention' # another is mlp
k_type: 'knn'
light_D: 290
light_C: 290
embed_color: 1
light_num_self_attention_blocks: 1
ray_dir_type: 'global'
perceiver_io_type: 'each_sample_loc'

load_init_pcd_type: 'grid' 

color_loss_weights: [1.0, 0.1, 0.1]
color_loss_items: ['ray_masked_coarse_raycolor', 'loss_alpha', 'loss_rgb']

prob_maximum_step: 150002 #500000 #250000 #800000
prob_freq: 100
prob_num_step: 2
prob_kernel_size: [3, 3, 3, 1, 1, 1]
maximum_epoch: 800000
prob_tiers: [100, 200]
test_freq: 50 #  #100 #1200 #1200 #30184 #30184 #50000
save_iter_freq: 50
prob_mode: 1 # 0, n, 1 t, 10 t&n
prob_thresh: 0.9
prob_mul: 0.4
gap: 0.4
knn_k: 8
relative_thresh: True

all_sample_loc: 1
new_local_knn: 1
clip_knn: 1

test_color_loss_items: ['coarse_raycolor', 'ray_miss_coarse_raycolor', 'ray_masked_coarse_raycolor']
visual_items: ['coarse_raycolor', 'gt_image', 'raypos_tensor', 'decoded_features']

agg_feat_xyz_mode: "None"
agg_alpha_xyz_mode: "None"
agg_color_xyz_mode: "None"
feature_init_method: "rand" #"rand" # "zeros"
agg_axis_weight: [1., 1., 1.]
agg_dist_pers: 20
radius_limit_scale: 4
depth_limit_scale: 0
vscale: [2, 2, 2]
kernel_size: [3, 3, 3]
query_size: [3, 3, 3]
vsize: [0.032, 0.032, 0.032]
wcoord_query: 1
z_depth_dim: 400
max_o: 610000
ranges: [-10.0, -10.0, -10.0, 10.0, 10.0, 10.0]
SR: 24
K: 8
P: 26
NN: 2
